title: "이협건 교수"
description: "AI, 클라우드, 빅데이터, 소프트웨어 엔지니어링 교육과 연구"
url: "https://prof.k-bigdata.kr"
baseurl: "" # 루트에서 운영하면 공백

remote_theme: mmistakes/minimal-mistakes@4.24.0

locale: "ko-KR"
timezone: "Asia/Seoul"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

seo:
  type: "Person"
  name: "이협건 교수"
  description: "AI, 클라우드, 빅데이터, 소프트웨어 엔지니어링 교육과 연구"

# Google Analytics (원하면 추적 ID 입력)
# google_analytics: G-XXXXXXXXXX

author:
  name: "이협건"
  avatar: "/assets/images/profile.jpg"
  bio: "한국폴리텍대학 서울강서캠퍼스 빅데이터소프트웨어공학과 교수"
  location: "Seoul, South Korea"
  links:
    - label: "학과 홈페이지"
      icon: "fas fa-graduation-cap"
      url: "https://ai.k-bigdata.kr/"
    - label: "졸업생 포트폴리오"
      icon: "fas fa-folder-open"
      url: "https://portfolio.k-bigdata.kr/"
    - label: "수시 1차 원서접수"
      icon: "fas fa-file-signature"
      url: "https://apply.jinhakapply.com/Notice/5041044/A"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hyeopgeon-lee"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:hglee67@kopo.ac.kr"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      css: "/assets/css/custom.css"

  - scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"

include:
  - _includes
  - _includes/head.html
  - _includes/head/custom.html

nav:
  - title: "홈"
    url: "/"
  - title: "연구실적"
    url: "/research/"
  - title: "교육"
    url: "/teaching/"
  - title: "기술 블로그"
    url: "/blog/"
